### ISSUE TITLE
Debian 10.13 Buster; curl install leaves me with glibc dependency error

### ISSUE THREAD

**Issue by jakobdalsgaard** [stalwartlabs/smtp-server#2]
Hi, did this:

```
curl --proto '=https' --tlsv1.2 -sSf https://smtp.stalw.art/install.sh | sudo sh
```

Ended up with this log output:

```
Mar 04 13:33:49 server3 stalwart-smtp[12366]: /usr/local/stalwart-smtp/bin/stalwart-smtp: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/stalwart-smtp/bin/stalwar
Mar 04 13:33:49 server3 stalwart-smtp[12366]: /usr/local/stalwart-smtp/bin/stalwart-smtp: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /usr/local/stalwart-smtp/bin/stalwar
Mar 04 13:33:49 server3 systemd[1]: stalwart-smtp.service: Main process exited, code=exited, status=1/FAILURE
Mar 04 13:33:49 server3 systemd[1]: stalwart-smtp.service: Failed with result 'exit-code'.
```

```
$ cat /etc/debian_version 
10.13
```

I'm not saying you _should_ support this setup, but at least the install.sh could say 'unsupported platform' or something :-)

**Comment by mdecimus** [comment]
Hi, thanks for the report. All binaries are compiled using Github workers and the oldest Linux distribution available is Ubuntu 20.04. It looks like Debian 10.13 comes with an even older GLIBC version, that is why the binaries cannot be executed.
In order to make Stalwart SMTP run in your platform you have three options:

1. Compile Stalwart SMTP from the source and replace the downloaded binary with the one you compiled. This should be the quickest/easiest way.
2. Upgrade your GLIBC version. This will be probably a nightmare.
3. Upgrade your server to the latest Debian version. This should be easier than (2).

In any case, I'll add to the script a check to verify the libc version before installing.
